// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten

package org.rover.sdk.xdr;


import java.io.IOException;

// === xdr source ============================================================

//  struct LedgerRCAMessages
//  {
//      uint32 ledgerSeq;
//      RCAEnvelope messages<>;
//  };

//  ===========================================================================
public class LedgerRCAMessages  {
  public LedgerRCAMessages () {}
  private Uint32 ledgerSeq;
  public Uint32 getLedgerSeq() {
    return this.ledgerSeq;
  }
  public void setLedgerSeq(Uint32 value) {
    this.ledgerSeq = value;
  }
  private RCAEnvelope[] messages;
  public RCAEnvelope[] getMessages() {
    return this.messages;
  }
  public void setMessages(RCAEnvelope[] value) {
    this.messages = value;
  }
  public static void encode(XdrDataOutputStream stream, LedgerRCAMessages encodedLedgerSCPMessages) throws IOException{
    Uint32.encode(stream, encodedLedgerSCPMessages.ledgerSeq);
    int messagessize = encodedLedgerSCPMessages.getMessages().length;
    stream.writeInt(messagessize);
    for (int i = 0; i < messagessize; i++) {
      RCAEnvelope.encode(stream, encodedLedgerSCPMessages.messages[i]);
    }
  }
  public static LedgerRCAMessages decode(XdrDataInputStream stream) throws IOException {
    LedgerRCAMessages decodedLedgerSCPMessages = new LedgerRCAMessages();
    decodedLedgerSCPMessages.ledgerSeq = Uint32.decode(stream);
    int messagessize = stream.readInt();
    decodedLedgerSCPMessages.messages = new RCAEnvelope[messagessize];
    for (int i = 0; i < messagessize; i++) {
      decodedLedgerSCPMessages.messages[i] = RCAEnvelope.decode(stream);
    }
    return decodedLedgerSCPMessages;
  }
}
