// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten

package org.rover.sdk.xdr;


import java.io.IOException;

// === xdr source ============================================================

//  struct RCABallot
//  {
//      uint32 counter; // n
//      Value value;    // x
//  };

//  ===========================================================================
public class RCABallot  {
  public RCABallot () {}
  private Uint32 counter;
  public Uint32 getCounter() {
    return this.counter;
  }
  public void setCounter(Uint32 value) {
    this.counter = value;
  }
  private Value value;
  public Value getValue() {
    return this.value;
  }
  public void setValue(Value value) {
    this.value = value;
  }
  public static void encode(XdrDataOutputStream stream, RCABallot encodedSCPBallot) throws IOException{
    Uint32.encode(stream, encodedSCPBallot.counter);
    Value.encode(stream, encodedSCPBallot.value);
  }
  public static RCABallot decode(XdrDataInputStream stream) throws IOException {
    RCABallot decodedSCPBallot = new RCABallot();
    decodedSCPBallot.counter = Uint32.decode(stream);
    decodedSCPBallot.value = Value.decode(stream);
    return decodedSCPBallot;
  }
}
