// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten

package org.rover.sdk.xdr;


import java.io.IOException;

// === xdr source ============================================================

//  struct RCAEnvelope
//  {
//      RCAStatement statement;
//      Signature signature;
//  };

//  ===========================================================================
public class RCAEnvelope  {
  public RCAEnvelope () {}
  private RCAStatement statement;
  public RCAStatement getStatement() {
    return this.statement;
  }
  public void setStatement(RCAStatement value) {
    this.statement = value;
  }
  private Signature signature;
  public Signature getSignature() {
    return this.signature;
  }
  public void setSignature(Signature value) {
    this.signature = value;
  }
  public static void encode(XdrDataOutputStream stream, RCAEnvelope encodedSCPEnvelope) throws IOException{
    RCAStatement.encode(stream, encodedSCPEnvelope.statement);
    Signature.encode(stream, encodedSCPEnvelope.signature);
  }
  public static RCAEnvelope decode(XdrDataInputStream stream) throws IOException {
    RCAEnvelope decodedSCPEnvelope = new RCAEnvelope();
    decodedSCPEnvelope.statement = RCAStatement.decode(stream);
    decodedSCPEnvelope.signature = Signature.decode(stream);
    return decodedSCPEnvelope;
  }
}
