// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten

package org.rover.sdk.xdr;


import java.io.IOException;

// === xdr source ============================================================

//  union RCAHistoryEntry switch (int v)
//  {
//  case 0:
//      RCAHistoryEntryV0 v0;
//  };

//  ===========================================================================
public class RCAHistoryEntry  {
  public RCAHistoryEntry () {}
  Integer v;
  public Integer getDiscriminant() {
    return this.v;
  }
  public void setDiscriminant(Integer value) {
    this.v = value;
  }
  private RCAHistoryEntryV0 v0;
  public RCAHistoryEntryV0 getV0() {
    return this.v0;
  }
  public void setV0(RCAHistoryEntryV0 value) {
    this.v0 = value;
  }
  public static void encode(XdrDataOutputStream stream, RCAHistoryEntry encodedSCPHistoryEntry) throws IOException {
  stream.writeInt(encodedSCPHistoryEntry.getDiscriminant().intValue());
  switch (encodedSCPHistoryEntry.getDiscriminant()) {
  case 0:
  RCAHistoryEntryV0.encode(stream, encodedSCPHistoryEntry.v0);
  break;
  }
  }
  public static RCAHistoryEntry decode(XdrDataInputStream stream) throws IOException {
  RCAHistoryEntry decodedSCPHistoryEntry = new RCAHistoryEntry();
  Integer discriminant = stream.readInt();
  decodedSCPHistoryEntry.setDiscriminant(discriminant);
  switch (decodedSCPHistoryEntry.getDiscriminant()) {
  case 0:
  decodedSCPHistoryEntry.v0 = RCAHistoryEntryV0.decode(stream);
  break;
  }
    return decodedSCPHistoryEntry;
  }
}
