// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten

package org.rover.sdk.xdr;


import java.io.IOException;

// === xdr source ============================================================

//  struct RCAQuorumSet
//  {
//      uint32 threshold;
//      PublicKey validators<>;
//      RCAQuorumSet innerSets<>;
//  };

//  ===========================================================================
public class RCAQuorumSet  {
  public RCAQuorumSet () {}
  private Uint32 threshold;
  public Uint32 getThreshold() {
    return this.threshold;
  }
  public void setThreshold(Uint32 value) {
    this.threshold = value;
  }
  private PublicKey[] validators;
  public PublicKey[] getValidators() {
    return this.validators;
  }
  public void setValidators(PublicKey[] value) {
    this.validators = value;
  }
  private RCAQuorumSet[] innerSets;
  public RCAQuorumSet[] getInnerSets() {
    return this.innerSets;
  }
  public void setInnerSets(RCAQuorumSet[] value) {
    this.innerSets = value;
  }
  public static void encode(XdrDataOutputStream stream, RCAQuorumSet encodedSCPQuorumSet) throws IOException{
    Uint32.encode(stream, encodedSCPQuorumSet.threshold);
    int validatorssize = encodedSCPQuorumSet.getValidators().length;
    stream.writeInt(validatorssize);
    for (int i = 0; i < validatorssize; i++) {
      PublicKey.encode(stream, encodedSCPQuorumSet.validators[i]);
    }
    int innerSetssize = encodedSCPQuorumSet.getInnerSets().length;
    stream.writeInt(innerSetssize);
    for (int i = 0; i < innerSetssize; i++) {
      RCAQuorumSet.encode(stream, encodedSCPQuorumSet.innerSets[i]);
    }
  }
  public static RCAQuorumSet decode(XdrDataInputStream stream) throws IOException {
    RCAQuorumSet decodedSCPQuorumSet = new RCAQuorumSet();
    decodedSCPQuorumSet.threshold = Uint32.decode(stream);
    int validatorssize = stream.readInt();
    decodedSCPQuorumSet.validators = new PublicKey[validatorssize];
    for (int i = 0; i < validatorssize; i++) {
      decodedSCPQuorumSet.validators[i] = PublicKey.decode(stream);
    }
    int innerSetssize = stream.readInt();
    decodedSCPQuorumSet.innerSets = new RCAQuorumSet[innerSetssize];
    for (int i = 0; i < innerSetssize; i++) {
      decodedSCPQuorumSet.innerSets[i] = RCAQuorumSet.decode(stream);
    }
    return decodedSCPQuorumSet;
  }
}
