// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten

package org.rover.sdk.xdr;


import java.io.IOException;

// === xdr source ============================================================

//  union RoverMessage switch (MessageType type)
//  {
//  case ERROR_MSG:
//      Error error;
//  case HELLO:
//      Hello hello;
//  case AUTH:
//      Auth auth;
//  case DONT_HAVE:
//      DontHave dontHave;
//  case GET_PEERS:
//      void;
//  case PEERS:
//      PeerAddress peers<>;
//  
//  case GET_TX_SET:
//      uint256 txSetHash;
//  case TX_SET:
//      TransactionSet txSet;
//  
//  case TRANSACTION:
//      TransactionEnvelope transaction;
//  
//  // RCA
//  case GET_SCP_QUORUMSET:
//      uint256 qSetHash;
//  case SCP_QUORUMSET:
//      RCAQuorumSet qSet;
//  case SCP_MESSAGE:
//      RCAEnvelope envelope;
//  case GET_SCP_STATE:
//      uint32 getSCPLedgerSeq; // ledger seq requested ; if 0, requests the latest
//  };

//  ===========================================================================
public class RoverMessage  {
  public RoverMessage () {}
  MessageType type;
  public MessageType getDiscriminant() {
    return this.type;
  }
  public void setDiscriminant(MessageType value) {
    this.type = value;
  }
  private Error error;
  public Error getError() {
    return this.error;
  }
  public void setError(Error value) {
    this.error = value;
  }
  private Hello hello;
  public Hello getHello() {
    return this.hello;
  }
  public void setHello(Hello value) {
    this.hello = value;
  }
  private Auth auth;
  public Auth getAuth() {
    return this.auth;
  }
  public void setAuth(Auth value) {
    this.auth = value;
  }
  private DontHave dontHave;
  public DontHave getDontHave() {
    return this.dontHave;
  }
  public void setDontHave(DontHave value) {
    this.dontHave = value;
  }
  private PeerAddress[] peers;
  public PeerAddress[] getPeers() {
    return this.peers;
  }
  public void setPeers(PeerAddress[] value) {
    this.peers = value;
  }
  private Uint256 txSetHash;
  public Uint256 getTxSetHash() {
    return this.txSetHash;
  }
  public void setTxSetHash(Uint256 value) {
    this.txSetHash = value;
  }
  private TransactionSet txSet;
  public TransactionSet getTxSet() {
    return this.txSet;
  }
  public void setTxSet(TransactionSet value) {
    this.txSet = value;
  }
  private TransactionEnvelope transaction;
  public TransactionEnvelope getTransaction() {
    return this.transaction;
  }
  public void setTransaction(TransactionEnvelope value) {
    this.transaction = value;
  }
  private Uint256 qSetHash;
  public Uint256 getQSetHash() {
    return this.qSetHash;
  }
  public void setQSetHash(Uint256 value) {
    this.qSetHash = value;
  }
  private RCAQuorumSet qSet;
  public RCAQuorumSet getQSet() {
    return this.qSet;
  }
  public void setQSet(RCAQuorumSet value) {
    this.qSet = value;
  }
  private RCAEnvelope envelope;
  public RCAEnvelope getEnvelope() {
    return this.envelope;
  }
  public void setEnvelope(RCAEnvelope value) {
    this.envelope = value;
  }
  private Uint32 getSCPLedgerSeq;
  public Uint32 getGetSCPLedgerSeq() {
    return this.getSCPLedgerSeq;
  }
  public void setGetSCPLedgerSeq(Uint32 value) {
    this.getSCPLedgerSeq = value;
  }
  public static void encode(XdrDataOutputStream stream, RoverMessage encodedRoverMessage) throws IOException {
  stream.writeInt(encodedRoverMessage.getDiscriminant().getValue());
  switch (encodedRoverMessage.getDiscriminant()) {
  case ERROR_MSG:
  Error.encode(stream, encodedRoverMessage.error);
  break;
  case HELLO:
  Hello.encode(stream, encodedRoverMessage.hello);
  break;
  case AUTH:
  Auth.encode(stream, encodedRoverMessage.auth);
  break;
  case DONT_HAVE:
  DontHave.encode(stream, encodedRoverMessage.dontHave);
  break;
  case GET_PEERS:
  break;
  case PEERS:
  int peerssize = encodedRoverMessage.getPeers().length;
  stream.writeInt(peerssize);
  for (int i = 0; i < peerssize; i++) {
    PeerAddress.encode(stream, encodedRoverMessage.peers[i]);
  }
  break;
  case GET_TX_SET:
  Uint256.encode(stream, encodedRoverMessage.txSetHash);
  break;
  case TX_SET:
  TransactionSet.encode(stream, encodedRoverMessage.txSet);
  break;
  case TRANSACTION:
  TransactionEnvelope.encode(stream, encodedRoverMessage.transaction);
  break;
  case GET_SCP_QUORUMSET:
  Uint256.encode(stream, encodedRoverMessage.qSetHash);
  break;
  case SCP_QUORUMSET:
  RCAQuorumSet.encode(stream, encodedRoverMessage.qSet);
  break;
  case SCP_MESSAGE:
  RCAEnvelope.encode(stream, encodedRoverMessage.envelope);
  break;
  case GET_SCP_STATE:
  Uint32.encode(stream, encodedRoverMessage.getSCPLedgerSeq);
  break;
  }
  }
  public static RoverMessage decode(XdrDataInputStream stream) throws IOException {
  RoverMessage decodedRoverMessage = new RoverMessage();
  MessageType discriminant = MessageType.decode(stream);
  decodedRoverMessage.setDiscriminant(discriminant);
  switch (decodedRoverMessage.getDiscriminant()) {
  case ERROR_MSG:
  decodedRoverMessage.error = Error.decode(stream);
  break;
  case HELLO:
  decodedRoverMessage.hello = Hello.decode(stream);
  break;
  case AUTH:
  decodedRoverMessage.auth = Auth.decode(stream);
  break;
  case DONT_HAVE:
  decodedRoverMessage.dontHave = DontHave.decode(stream);
  break;
  case GET_PEERS:
  break;
  case PEERS:
  int peerssize = stream.readInt();
  decodedRoverMessage.peers = new PeerAddress[peerssize];
  for (int i = 0; i < peerssize; i++) {
    decodedRoverMessage.peers[i] = PeerAddress.decode(stream);
  }
  break;
  case GET_TX_SET:
  decodedRoverMessage.txSetHash = Uint256.decode(stream);
  break;
  case TX_SET:
  decodedRoverMessage.txSet = TransactionSet.decode(stream);
  break;
  case TRANSACTION:
  decodedRoverMessage.transaction = TransactionEnvelope.decode(stream);
  break;
  case GET_SCP_QUORUMSET:
  decodedRoverMessage.qSetHash = Uint256.decode(stream);
  break;
  case SCP_QUORUMSET:
  decodedRoverMessage.qSet = RCAQuorumSet.decode(stream);
  break;
  case SCP_MESSAGE:
  decodedRoverMessage.envelope = RCAEnvelope.decode(stream);
  break;
  case GET_SCP_STATE:
  decodedRoverMessage.getSCPLedgerSeq = Uint32.decode(stream);
  break;
  }
    return decodedRoverMessage;
  }
}
